<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251121053255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attendances (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, attendance_date DATE NOT NULL, clock_in_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, clock_out_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, break_minutes INT DEFAULT NULL, location_data JSON DEFAULT NULL, notes VARCHAR(500) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C6B8FD4A76ED395 ON attendances (user_id)');
        $this->addSql('ALTER TABLE attendances ADD CONSTRAINT FK_9C6B8FD4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendances DROP CONSTRAINT FK_9C6B8FD4A76ED395');
        $this->addSql('DROP TABLE attendances');
    }
}
